##################################################################################################
# ProductPage service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
spec:
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: 9080  
    protocol: TCP
    name: http
  selector:
    app: productpage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      containers:
      - name: productpage
        image: dockeroscarperez/productpage
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
